import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  // Header Styles
  headerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    paddingTop: 10,
    paddingBottom: 10,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    zIndex: 10,
  },
  logoImage: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    borderWidth: 1.5,
    borderColor: '#DAA520',
  },
  headerSearchContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f5f5f5',
    borderRadius: 8,
    paddingHorizontal: 10,
    height: 40,
    marginHorizontal: 10,
  },
  headerSearchInput: {
    flex: 1,
    height: 40,
    fontSize: 14,
    color: '#333',
    padding: 0,
    marginLeft: 5,
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    marginLeft: 12,
    position: 'relative',
  },
  badge: {
    position: 'absolute',
    top: -4,
    right: -6,
    backgroundColor: '#ff0000',
    borderRadius: 9,
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#fff',
  },
  badgeText: {
    color: '#fff',
    fontSize: 9,
    fontFamily: 'OpenSans-Regular',
    fontWeight: 'bold',
  },
  // Carousel Styles
  carouselContainer: {
    height: 150,
    width: '100%',
  },
  carouselSlide: {
    width: width,
    height: 150,
    paddingHorizontal: 15,
  },
  carouselImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    borderRadius: 15, // Adds the framework/rounded edges
  },
  paginationContainer: {
    flexDirection: 'row',
    position: 'absolute',
    bottom: 15,
    alignSelf: 'center',
  },
  paginationDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    marginHorizontal: 4,
  },
  paginationDotActive: {
    backgroundColor: '#FFC107',
    width: 24,
    height: 10,
    borderRadius: 5,
  },
  // Category Styles
  sectionContainer: {
    paddingVertical: 25,
    paddingHorizontal: 20,
    backgroundColor: '#ffffff',
  },
  categoryGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 5,
  },
  categoryItem: {
    alignItems: 'center',
    width: (width - 40) / 4,
    marginBottom: 15,
  },
  categoryImageWrapper: {
    width: 70,
    height: 70,
    marginBottom: 8,
    borderRadius: 35,
    borderWidth: 2,
    borderColor: '#FF8C00',
    backgroundColor: '#fff',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  categoryName: {
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  iconButton: {
    marginLeft: 12,
    position: 'relative',
  },
  badge: {
    position: 'absolute',
    top: -4,
    right: -6,
    backgroundColor: '#ff0000',
    borderRadius: 9,
    width: 16,
    height: 16,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#fff',
  },
  badgeText: {
    color: '#fff',
    fontSize: 9,
    fontFamily: 'OpenSans-Regular',
    fontWeight: 'bold',
  },
  // Carousel Styles
  carouselContainer: {
    height: 150,
    width: '100%',
  },
  carouselSlide: {
    width: width,
    height: 150,
    paddingHorizontal: 15,
  },
  carouselImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
    borderRadius: 15, // Adds the framework/rounded edges
  },
  paginationContainer: {
    flexDirection: 'row',
    position: 'absolute',
    bottom: 15,
    alignSelf: 'center',
  },
  paginationDot: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    marginHorizontal: 4,
  },
  paginationDotActive: {
    backgroundColor: '#FFC107',
    width: 24,
    height: 10,
    borderRadius: 5,
  },
  // Category Styles
  sectionContainer: {
    paddingVertical: 25,
    paddingHorizontal: 20,
    backgroundColor: '#ffffff',
  },
  categoryGrid: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 5,
  },
  categoryItem: {
    alignItems: 'center',
    width: (width - 40) / 4,
    marginBottom: 15,
  },
  categoryImageWrapper: {
    width: 70,
    height: 70,
    marginBottom: 8,
    borderRadius: 35,
    borderWidth: 2,
    borderColor: '#FF8C00',
    backgroundColor: '#fff',
    overflow: 'hidden',
    justifyContent: 'center',
    alignItems: 'center',
  },
  categoryImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  categoryName: {
    color: '#282c3f',
    fontFamily: 'OpenSans-Regular',
    fontWeight: '700',
    fontSize: 16,
  },
  // Button Styles
  buttonContainer: {
    marginTop: 40,
    marginBottom: 20,
    alignItems: 'center',
  },
  actionButton: {
    backgroundColor: '#FFA500', // matches linear-gradient(135deg, #FFA500 0%, #FF7F50 100%) fallback
    paddingVertical: 15,
    paddingHorizontal: 40,
    borderRadius: 50,
    shadowColor: '#FFA500',
    shadowOffset: { width: 0, height: 5 },
    shadowOpacity: 0.3,
    shadowRadius: 15,
    elevation: 5,
  },
  actionButtonText: {
    color: '#ffffff',
    fontFamily: 'OpenSans-Regular',
    fontWeight: 'bold',
    fontSize: 16,
  },
  // Brands Section Styles
  brandsSection: {
    paddingVertical: 25,
    backgroundColor: '#ffffff',
  },
  brandsHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    paddingHorizontal: 20,
    marginBottom: 20,
  },
  brandsTitle: {
    fontSize: 20,
    fontFamily: 'OpenSans-Regular',
    fontWeight: 'bold',
    color: '#282c3f',
  },
  brandsSubtitle: {
    fontSize: 13,
    fontFamily: 'OpenSans-Regular',
    color: '#888',
    marginTop: 4,
  },
  brandsSeeAll: {
    fontSize: 14,
    color: '#FFA500',
    fontFamily: 'OpenSans-Regular',
    fontWeight: 'bold',
  },
  brandsScrollContainer: {
    paddingHorizontal: 15,
  },
  brandItem: {
    alignItems: 'center',
    marginHorizontal: 10,
    width: 76,
  },
  brandIconWrapper: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: '#ffffff',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#f0f0f0',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 3,
    elevation: 2,
    overflow: 'hidden',
  },
  brandImage: {
    width: '65%',
    height: '65%',
  },
  brandText: {
    fontSize: 12,
    fontFamily: 'OpenSans-Regular',
    color: '#333',
    textAlign: 'center',
    fontWeight: '500',
  },
  // Occasion Section Styles
  occasionSection: {
    paddingVertical: 30,
    backgroundColor: '#f9f9f9',
  },
  occasionTitleContainer: {
    flexDirection: 'column',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 20,
  },
  occasionTitlePart1: {
    fontSize: 28,
    fontFamily: 'OpenSans-Regular',
    fontWeight: '800',
    color: '#282c3f',
    textAlign: 'center',
  },
  occasionTitlePart2: {
    fontSize: 28,
    fontFamily: 'OpenSans-Regular',
    fontWeight: '800',
    color: '#FFA500',
    textAlign: 'center',
    marginTop: 5,
  },

  filtersContainer: {
    paddingHorizontal: 15,
    marginBottom: 20,
    flexDirection: 'row',
    alignItems: 'center',
  },
  filterPill: {
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
    borderWidth: 1,
    borderColor: '#eaeaea',
    backgroundColor: '#ffffff',
    marginRight: 10,
  },
  filterPillActive: {
    backgroundColor: '#FFA500',
    borderColor: '#FFA500',
    shadowColor: '#FFA500',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  filterText: {
    fontSize: 14,
    fontFamily: 'OpenSans-Regular',
    fontWeight: 'bold',
    color: '#333',
  },
  filterTextActive: {
    color: '#ffffff',
  },
  outfitCardsContainer: {
    paddingHorizontal: 15,
  },
  outfitCard: {
    width: width * 0.45,
    marginRight: 15,
    borderRadius: 15,
    overflow: 'hidden',
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#eee',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  outfitImageContainer: {
    width: '100%',
    height: 180,
    position: 'relative',
  },
  outfitImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  addToBagButton: {
    position: 'absolute',
    top: 10,
    right: 10,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(0,0,0,0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#ffffff',
  },
  outfitDetails: {
    padding: 15,
    paddingBottom: 18,
  },
  outfitTitle: {
    fontSize: 14,
    fontFamily: 'OpenSans-Regular',
    fontWeight: 'bold',
    color: '#282c3f',
    marginBottom: 4,
  },
  outfitBrand: {
    fontSize: 12,
    fontFamily: 'OpenSans-Regular',
    color: '#888',
    textTransform: 'uppercase',
    marginBottom: 8,
  },
  dashedLine: {
    borderBottomWidth: 1,
    borderColor: '#eee',
    borderStyle: 'dashed',
    marginBottom: 8,
  },
  priceRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  priceItem: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  priceLabel: {
    fontSize: 10,
    fontFamily: 'OpenSans-Regular',
    color: '#888',
    marginLeft: 4,
    marginRight: 8,
    fontWeight: 'bold',
  },
  rentPrice: {
    fontSize: 14,
    fontFamily: 'OpenSans-Regular',
    fontWeight: 'bold',
    color: '#FFA500',
  },
  buyPrice: {
    fontSize: 12,
    fontFamily: 'OpenSans-Regular',
    fontWeight: 'bold',
    color: '#333',
  },
  // Brands Modal Styles
  brandsModalContainer: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  brandsModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  brandsModalTitle: {
    fontSize: 20,
    fontFamily: 'OpenSans-Regular',
    fontWeight: 'bold',
    color: '#282c3f',
  },
  brandsModalGrid: {
    padding: 10,
  },
  brandGridItem: {
    flex: 1,
    alignItems: 'center',
    marginBottom: 20,
    maxWidth: '25%', // 4 columns
  },
});

export default styles;
